import { loader } from "fumadocs-core/source";

import { docs } from "@/.source/server";

/**
 * `docs` here is the fumadocs-mdx codegen output for `source.config.ts`'s `defineDocs({ dir:
 * "content/docs" })` — not that config object itself. `.source/` (gitignored, regenerated by
 * `next dev`/`next build` via the `createMDX` wrap in next.config.ts) has no plain `index.ts`:
 * fumadocs-mdx@15's index-file plugin only ever emits `server.ts`/`browser.ts`/`dynamic.ts`
 * (verified directly from its own compiled plugin source, not assumed from older docs) —
 * `server.ts` is the one that exports `docs` with `toFumadocsSource()` for a server component.
 */
export const source = loader({
  baseUrl: "/docs",
  source: docs.toFumadocsSource(),
});
