#!/usr/bin/env node
// Compiles src/style.css (real Tailwind classes, real @config) through Tailwind's own PostCSS
// pipeline into static, scoped CSS text, then writes that text as a plain TS string constant to
// src/generated-style.ts. index.ts imports GENERATED_STYLE from that file and inlines it into the
// shadow root's own <style> tag at render time — this is what makes Tailwind a build-time-only
// tool here: nothing about Tailwind, PostCSS, or @ferryline/design-tokens exists any more once this
// script has run; the output is inert CSS text baked into the built JS bundle.
//
// Run by `pnpm build` (see package.json) BEFORE tsup, not as a tsup plugin — tsup's own esbuild
// pipeline has no CSS-processing hook, and the alternative (a custom esbuild plugin re-implementing
// what PostCSS already does) would be needless complexity for a one-shot, one-file compile step.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import tailwindcss from "@tailwindcss/postcss";
import postcss from "postcss";

const here = fileURLToPath(new URL(".", import.meta.url));
const inputPath = `${here}../src/style.css`;
const outputPath = `${here}../src/generated-style.ts`;

const css = readFileSync(inputPath, "utf8");
const result = await postcss([tailwindcss()]).process(css, {
  from: inputPath,
  to: outputPath,
});

for (const warning of result.warnings()) {
  // A real PostCSS/Tailwind warning (a bad @config path, an unresolvable class) — surfaced as a
  // build failure rather than silently shipping whatever partial CSS Tailwind produced anyway.
  console.error(warning.toString());
}
if (result.warnings().length > 0) {
  process.exit(1);
}

const compiled = result.css;

// A sanity check, not a style-correctness check: if Tailwind's own directives (@import
// "tailwindcss", @config) survive verbatim into the output, the compile silently no-opped instead
// of actually processing the file — fail loudly rather than ship source-looking text as "CSS".
if (compiled.includes("@import") && compiled.includes("tailwindcss")) {
  throw new Error(
    'build-style.mjs: compiled output still contains an unresolved @import "tailwindcss" — ' +
      "the Tailwind PostCSS step did not run correctly.",
  );
}

const banner =
  "// AUTO-GENERATED by scripts/build-style.mjs from src/style.css — do not edit by hand.\n" +
  "// Regenerate with `pnpm build` (or `node scripts/build-style.mjs` directly).\n";

writeFileSync(outputPath, `${banner}export const GENERATED_STYLE = ${JSON.stringify(compiled)};\n`);

console.log(
  `build-style.mjs: compiled src/style.css -> src/generated-style.ts (${String(compiled.length)} bytes of CSS)`,
);
